wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    code_path: code/dapg/examples/job_script.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1661524821.670323
    t:
      1:
      - 1
      - 3
      - 55
      2:
      - 1
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.7.0
      5: 0.13.2
      8:
      - 5
config:
  desc: null
  value: rl_scratch.txt
output:
  desc: null
  value: rl_scratch_exp
record_video:
  desc: null
  value: true
record_video_interval:
  desc: null
  value: 10000
record_video_length:
  desc: null
  value: 100
render:
  desc: null
  value: false
wandb_activate:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: quantumiracle
wandb_group:
  desc: null
  value: ''
wandb_name:
  desc: null
  value: relocate-v0_NPG
wandb_project:
  desc: null
  value: h_a_n_d___d_a_p_g
